---
- hosts: rhel8_chrony_client_hosts
  tasks:
    - name: copy_chrony_client_conf_to_remote
      ansible.builtin.copy:
        src: "{{playbook_dir}}/conf/chrony_client.conf"
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'
        ###COMMENT this if selinux is disabled
        seuser: system_u
        setype: etc_t
        serole: object_r
        selevel: s0
        ###COMMENT this if selinux is disabled
        backup: yes
      register: copy_chrony_client_conf_to_remote_res

######################################################

    - name: enable_n_restart_chronyd
      ansible.builtin.systemd:
        name: chronyd.service
        state: restarted
        enabled: yes
        masked: no
      when: copy_chrony_client_conf_to_remote_res.changed==true
