---
- hosts: rhel8_network_scripts_hosts
  tasks:
    - name: "check_for_ifcfg_dynamic_task_for_upd"
      delegate_to: localhost
      stat:
        path: "{{playbook_dir}}/{{inventory_hostname}}_upd.yml"
      register: is_ifcfg_dynamic_task_for_upd

######################################################

    - name: "check_for_ifcfg_dynamic_task_for_del"
      delegate_to: localhost
      stat:
        path: "{{playbook_dir}}/{{inventory_hostname}}_del.yml"
      register: is_ifcfg_dynamic_task_for_del

######################################################

    - name: "run_ifcfg_dynamic_upd_task_if_exists"
      ansible.builtin.include_tasks: "{{playbook_dir}}/{{inventory_hostname}}_upd.yml"
      when: is_ifcfg_dynamic_task_for_upd.stat.exists==true

######################################################

    - name: "run_ifcfg_dynamic_del_task_if_exists"
      ansible.builtin.include_tasks: "{{playbook_dir}}/{{inventory_hostname}}_upd.yml"
      when: is_ifcfg_dynamic_task_for_del.stat.exists==true

