---
- hosts: rhel8_nfs_client_conf_dedic_app
  tasks:
    - name: install_nfs_packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: installed
      with_items:
        - nfs-utils
        - nfs4-acl-tools
