---
- hosts: network_scripts_conf_dedic_app_v1
  tasks:
    - name: "run ifcfg_backup_task_main"
      ansible.builtin.include_tasks: "{{playbook_dir}}/tasks/ifcfg_backup_task_main.yml"

######################################################

    - name: "run ifcfg_backup_collect_raw_network_data_task"
      ansible.builtin.include_tasks: "{{playbook_dir}}/tasks/ifcfg_backup_collect_raw_network_data_task.yml"

