---
- hosts: rhel8_network_scripts_hosts
  tasks:
    - name: install_network_packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: installed
      with_items:
        - network-scripts
        - procps-ng
