---
- hosts: conf_network_dedic_app_v1
  tasks:
    - name: "run conf_backup_task_main"
      ansible.builtin.include_tasks: "{{inventory_dir}}/04_tasks/conf_backup_task_main.yml"

######################################################

    - name: "run conf_local_backup_for_temp_apply_task"
      ansible.builtin.include_tasks: "{{inventory_dir}}/04_tasks/conf_local_backup_for_temp_apply_task.yml"

######################################################

    - name: "run conf_backup_collect_raw_network_data_task"
      ansible.builtin.include_tasks: "{{inventory_dir}}/04_tasks/conf_backup_collect_raw_network_data_task.yml"
