---
- import_playbook: "{{inventory_dir}}/03_playbooks/just_install_network_scripts_playbook.yml"
- import_playbook: "{{inventory_dir}}/03_playbooks/check_network_scripts_serv_is_started_playbook.yml"
#- import_playbook: "{{playbook_dir}}/dyn_ifcfg_playbooks/dynamic_ifcfg_loader.yml"
