# APPLY IPSET, ZONES, POLICIES
######################################################STEP 1. Check for locally generated fwrules files is exist (begin)
# fill vars: recreate_permanent_ipsets_sh_exists_at_local, recreate_temporary_ipsets_sh_exists_at_local, 
# recreate_fw_zones_sh_exists_at_local, recreate_policies_sh_exists_at_local, rollback_fwrules_changes_sh_exists_at_local
# permanent_ipsets_flag_file_exists_at_local, temporary_ipsets_flag_file_exists_at_local

- name: "Check if exists at localhost 'INV-HOST/recreate_permanent_ipsets.sh' for apply"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/recreate_permanent_ipsets.sh"
  register: recreate_permanent_ipsets_sh_exists_at_local

######

- name: "Check if exists at localhost 'INV-HOST/recreate_temporary_ipsets.sh' for apply"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/recreate_temporary_ipsets.sh"
  register: recreate_temporary_ipsets_sh_exists_at_local

######

- name: "Check if exists at localhost 'INV-HOST/recreate_fw_zones.sh' for apply"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/recreate_fw_zones.sh"
  register: recreate_fw_zones_sh_exists_at_local

######

- name: "Check if exists at localhost 'INV-HOST/recreate_policies.sh' for apply"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/recreate_policies.sh"
  register: recreate_policies_sh_exists_at_local

######

- name: "Check if exists at localhost 'INV-HOST/permanent_ipsets_flag_file' for apply"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/permanent_ipsets_flag_file"
  register: permanent_ipsets_flag_file_exists_at_local

######

- name: "Check if exists at localhost 'INV-HOST/temporary_ipsets_flag_file' for apply"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/temporary_ipsets_flag_file"
  register: temporary_ipsets_flag_file_exists_at_local

######

- name: "Check if exists at localhost 'INV-HOST/rollback_fwrules_changes.sh'"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/rollback_fwrules_changes.sh"
  register: rollback_fwrules_changes_sh_exists_at_local

######################################################STEP 1. Check for locally generated fwrules files is exist (end)

######################################################STEP 2. Check for remote files is exist (begin)
# fill vars: recreate_permanent_ipsets_sh_exists_at_remote, recreate_temporary_ipsets_sh_exists_at_remote
# recreate_fw_zones_sh_exists_at_remote, recreate_policies_sh_exists_at_remote
# permanent_ipsets_flag_file_exists_at_remote, temporary_ipsets_flag_file_exists_at_remote

- name: "Check if exists at remote 'recreate_permanent_ipsets.sh' for apply"
  ansible.builtin.stat:
    path: "~/ansible_helpers/conf_firewalld/recreate_permanent_ipsets.sh"
  register: recreate_permanent_ipsets_sh_exists_at_remote

######

- name: "Check if exists at remote 'recreate_temporary_ipsets.sh' for apply"
  ansible.builtin.stat:
    path: "~/ansible_helpers/conf_firewalld/recreate_temporary_ipsets.sh"
  register: recreate_temporary_ipsets_sh_exists_at_remote

######

- name: "Check if exists at remote 'recreate_fw_zones.sh' for apply"
  ansible.builtin.stat:
    path: "~/ansible_helpers/conf_firewalld/recreate_fw_zones.sh"
  register: recreate_fw_zones_sh_exists_at_remote

######

- name: "Check if exists at remote 'recreate_policies.sh' for apply"
  ansible.builtin.stat:
    path: "~/ansible_helpers/conf_firewalld/recreate_policies.sh"
  register: recreate_policies_sh_exists_at_remote

######

- name: "Check if exists at remote 'permanent_ipsets_flag_file' for apply"
  ansible.builtin.stat:
    path: "~/ansible_helpers/conf_firewalld/permanent_ipsets_flag_file"
  register: permanent_ipsets_flag_file_exists_at_remote

######

- name: "Check if exists at remote 'temporary_ipsets_flag_file' for apply"
  ansible.builtin.stat:
    path: "~/ansible_helpers/conf_firewalld/temporary_ipsets_flag_file"
  register: temporary_ipsets_flag_file_exists_at_remote

######################################################STEP 2. Check for remote files is exist (end)

######################################################STEP 3. Create dirs 'conf_firewalld' and 'apply_run_info' at remote side (begin)

- name: "Create dir '~/ansible_helpers/conf_firewalld' at remote if not exists"
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld"
    state: directory

######

- name: "Create dir '~/ansible_helpers/conf_firewalld/apply_run_info' at remote if not exists"
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld/apply_run_info"
    state: directory

######################################################STEP 3. Create dirs 'conf_firewalld' and 'apply_run_info' at remote side (end)

######################################################STEP 4. Operations with dirs for ipsets content at remote side (begin)

- name: "Check if exists at remote 'permanent_ipsets' for apply"
  ansible.builtin.stat:
    path: "~/ansible_helpers/conf_firewalld/permanent_ipsets"
  register: permanent_ipsets_dir_exists_at_remote

######

- name: "Check if exists at remote 'temporary_ipsets' for apply"
  ansible.builtin.stat:
    path: "~/ansible_helpers/conf_firewalld/temporary_ipsets"
  register: temporary_ipsets_dir_exists_at_remote

######

- name: "Create 'prev_permanent_ipsets' and move content of 'permanent_ipsets' to it at remote if need"
  ansible.builtin.shell: cd ~/ansible_helpers/conf_firewalld && rm -rf prev_permanent_ipsets && mv permanent_ipsets prev_permanent_ipsets
  when: permanent_ipsets_dir_exists_at_remote.stat.exists==true

######

- name: "Create 'prev_temporary_ipsets' and move content of 'temporary_ipsets' to it at remote if need"
  ansible.builtin.shell: cd ~/ansible_helpers/conf_firewalld && rm -rf prev_temporary_ipsets && mv temporary_ipsets prev_temporary_ipsets
  when: temporary_ipsets_dir_exists_at_remote.stat.exists==true

######

- name: "Create dir '~/ansible_helpers/conf_firewalld/permanent_ipsets' at remote if not exists"
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld/permanent_ipsets"
    state: directory

######

- name: "Create dir '~/ansible_helpers/conf_firewalld/temporary_ipsets' at remote if not exists"
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld/temporary_ipsets"
    state: directory

######

- name: "Copy 'permanent_ipsets' content to remote"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/permanent_ipsets/"
    dest: "~/ansible_helpers/conf_firewalld/permanent_ipsets/"

######

- name: "Copy 'temporary_ipsets' content to remote"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/temporary_ipsets/"
    dest: "~/ansible_helpers/conf_firewalld/temporary_ipsets/"

######################################################STEP 4. Operations with dirs for ipsets content at remote side (end)

######################################################STEP 5. Make prev copies if need (begin)
# Prev copies: recreate_permanent_ipsets.sh, recreate_temporary_ipsets.sh
# recreate_fw_zones.sh, recreate_policies.sh, permanent_ipsets_flag_file, temporary_ipsets_flag_file

- name: "Make copy of 'recreate_permanent_ipset.sh' at remote if need"
  ansible.builtin.copy:
    src: "~/ansible_helpers/conf_firewalld/recreate_permanent_ipsets.sh"
    dest: "~/ansible_helpers/conf_firewalld/prev_recreate_permanent_ipsets.sh"
    remote_src: yes
    force: yes
    mode: '0770'
  when: recreate_permanent_ipsets_sh_exists_at_remote.stat.exists==true

######

- name: "Make copy of 'recreate_temporary_ipset.sh' at remote"
  ansible.builtin.copy:
    src: "~/ansible_helpers/conf_firewalld/recreate_temporary_ipsets.sh"
    dest: "~/ansible_helpers/conf_firewalld/prev_recreate_temporary_ipsets.sh"
    remote_src: yes
    force: yes
    mode: '0770'
  when: recreate_temporary_ipsets_sh_exists_at_remote.stat.exists==true

######

- name: "Make copy of 'recreate_fw_zones.sh' at remote"
  ansible.builtin.copy:
    src: "~/ansible_helpers/conf_firewalld/recreate_fw_zones.sh"
    dest: "~/ansible_helpers/conf_firewalld/prev_recreate_fw_zones.sh"
    remote_src: yes
    force: yes
    mode: '0770'
  when: recreate_fw_zones_sh_exists_at_remote.stat.exists==true

######

- name: "Make copy of 'recreate_policies.sh' at remote"
  ansible.builtin.copy:
    src: "~/ansible_helpers/conf_firewalld/recreate_policies.sh"
    dest: "~/ansible_helpers/conf_firewalld/prev_recreate_policies.sh"
    remote_src: yes
    force: yes
    mode: '0770'
  when: recreate_policies_sh_exists_at_remote.stat.exists==true

######################################################STEP 5. Make copies of 'recreate_permanent_ipsets.sh' and 'recreate_temporary_ipsets.sh' if need (end)

######################################################STEP 6. Copy (local->remote) recreated fwrules-files and rollback-script to remote if need (begin)

- name: "Copy 'recreate_permanent_ipsets.sh' to remote"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/recreate_permanent_ipsets.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_permanent_ipsets.sh"
    mode: '0770'
  register: copy_recreate_permanent_ipset_to_remote_res
  when: recreate_permanent_ipsets_sh_exists_at_local.stat.exists==true

######

- name: "Copy 'recreate_temporary_ipsets.sh' to remote"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/recreate_temporary_ipsets.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_temporary_ipsets.sh"
    mode: '0770'
  register: copy_recreate_temporary_ipset_to_remote_res
  when: recreate_temporary_ipsets_sh_exists_at_local.stat.exists==true

######

- name: "Copy 'recreate_fw_zones.sh' to remote"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/recreate_fw_zones.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_fw_zones.sh"
    mode: '0770'
  register: copy_recreate_fw_zones_to_remote_res
  when: recreate_fw_zones_sh_exists_at_local.stat.exists==true

######

- name: "Copy 'recreate_policies.sh' to remote if need"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/recreate_policies.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_policies.sh"
    owner: root
    group: root
    mode: '0770'
  register: copy_recreate_policies_to_remote_res
  when: recreate_policies_sh_exists_at_local.stat.exists==true

######

- name: "Copy 'rollback_fwrules_changes.sh' to remote if need"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/rollback_fwrules_changes.sh"
    dest: "~/ansible_helpers/conf_firewalld/rollback_fwrules_changes.sh"
    owner: root
    group: root
    mode: '0770'
  when: rollback_fwrules_changes_sh_exists_at_local.stat.exists==true

######

- name: "Copy 're_add_ipsets_content.sh' to remote"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/re_add_ipsets_content.sh"
    dest: "~/ansible_helpers/conf_firewalld/re_add_ipsets_content.sh"
    mode: '0770'

######

- name: "Copy 'apply_fwrules.sh' to remote"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/apply_fwrules.sh"
    dest: "~/ansible_helpers/conf_firewalld/apply_fwrules.sh"
    mode: '0770'

######################################################STEP 6. Copy (local->remote) recreated fwrules-files and rollback-script to remote if need (end)

######################################################STEP 7. Create apply-run-info-files at remote side (begin)

- name: "Create apply-run-info-file 'recreate_permanent_ipsets_changed' at remote"
  ansible.builtin.shell: touch ~/ansible_helpers/conf_firewalld/apply_run_info/recreate_permanent_ipsets_changed
  when: copy_recreate_permanent_ipset_to_remote_res.changed==true

######

- name: "Create apply-run-info-file 'recreate_temporary_ipsets_changed' at remote"
  ansible.builtin.shell: touch ~/ansible_helpers/conf_firewalld/apply_run_info/recreate_temporary_ipsets_changed
  when: copy_recreate_temporary_ipset_to_remote_res.changed==true

######

- name: "Create apply-run-info-file 'recreate_fw_zones_changed' at remote"
  ansible.builtin.shell: touch ~/ansible_helpers/conf_firewalld/apply_run_info/recreate_fw_zones_changed
  when: copy_recreate_fw_zones_to_remote_res.changed==true

######

- name: "Create apply-run-info-file 'recreate_policies_changed' at remote"
  ansible.builtin.shell: touch ~/ansible_helpers/conf_firewalld/apply_run_info/recreate_policies_changed
  when: copy_recreate_policies_to_remote_res.changed==true

######

- name: "Create apply-run-info-file 'rollback_fwrules_need_run' at remote"
  ansible.builtin.shell: touch ~/ansible_helpers/conf_firewalld/apply_run_info/rollback_fwrules_need_run
  when: rollback_fwrules_changes_sh_exists_at_local.stat.exists==true

######################################################STEP 7. Create apply-run-info-files at remote side (end)
