- name: "Collect and save network data to user home dir at remote"
  ansible.builtin.shell: ip -o addr > ~/ansible_helpers/conf_firewalld/tmp/ip_addr

######################################################

- name: "Create directory for raw network data (network_data-dir) at remote"
  ansible.builtin.file:
    path: "{{playbook_dir}}/fwrules_backup_from_remote/network_data"
    state: directory
  delegate_to: localhost

######################################################

- name: "Fetch raw network data from remote to local"
  ansible.builtin.fetch:
    flat: yes
    src: "~/ansible_helpers/conf_firewalld/tmp/{{item}}"
    dest: "{{playbook_dir}}/fwrules_backup_from_remote/network_data/{{inventory_hostname}}_{{item}}"
  with_items:
    - "ip_addr"
