- name: create_dir "ansible_helpers/conf_firewalld" if not exists
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld"
    state: directory

######################################################

- name: create_dir "ansible_helpers/conf_firewalld/apply_info" if not exists
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld/appy_info"
    state: directory

######################################################

- name: Remove file '~/ansible_helpers/conf_firewalld/etc_firewalld.zip' before archive '/etc/firewalld'
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld/etc_firewalld.zip"
    state: absent

######################################################

- name: Compress directory '/etc/firewalld' into '~/ansible_helpers/conf_firewalld/etc_firewalld.zip'
  archive:
    path: /etc/firewalld
    dest: "~/ansible_helpers/conf_firewalld/etc_firewalld.zip"
    format: zip

######################################################

- name: collect and save output of 'firewall-cmd --list-all-zones'
  ansible.builtin.shell: firewall-cmd --list-all-zones > ~/ansible_helpers/conf_firewalld/fw_list_all_zones.txt

######################################################

- name: fetch fw-backup-files
  ansible.builtin.fetch:
    flat: yes
    src: "~/ansible_helpers/conf_firewalld/{{item}}"
    dest: "{{playbook_dir}}/fwrules_backup_from_remote/history/{{ansible_date_time.iso8601_basic_short}}/{{inventory_hostname}}/{{item}}"
  with_items:
    - "fw_list_all_zones.txt"
    - "etc_firewalld.zip"

######################################################

- name: Create directory for actual fwrules-files (now-dir)
  ansible.builtin.file:
    path: "{{playbook_dir}}/fwrules_backup_from_remote/now/{{inventory_hostname}}"
    state: directory
  delegate_to: localhost

######################################################

- name: Copy 'fw_list_all_zones.txt' from history-dir to now-dir
  ansible.builtin.copy:
    src: "{{playbook_dir}}/fwrules_backup_from_remote/history/{{ansible_date_time.iso8601_basic_short}}/{{inventory_hostname}}/{{item}}"
    dest: "{{playbook_dir}}/fwrules_backup_from_remote/now/{{inventory_hostname}}/{{item}}"
  delegate_to: localhost
  with_items:
    - "fw_list_all_zones.txt"
    - "etc_firewalld.zip"
