# APPLY IPSET, ZONES, POLICIES
- name: "if exists 'INV-HOST_recreate_ipsets.sh' for apply"
  delegate_to: localhost
  stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_ipsets.sh"
  register: recreate_ipsets_sh_exists

######################################################

- name: "if exists 'INV-HOST_recreate_fw_zones.sh' for apply"
  delegate_to: localhost
  stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_fw_zones.sh"
  register: recreate_fw_zones_sh_exists

######################################################

- name: "if exists 'INV-HOST_recreate_policies.sh' for apply"
  delegate_to: localhost
  stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_policies.sh"
  register: recreate_policies_sh_exists

######################################################

- name: create_dir "ansible_helpers/conf_firewalld"
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld"
    state: directory

######################################################

- name: copy_recreate_ipset_to_remote
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_ipsets.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_ipsets.sh"
    owner: root
    group: root
    mode: '0770'
    backup: yes
  register: copy_recreate_ipset_to_remote_res
  when: recreate_ipsets_sh_exists.stat.exists==true

######################################################

- name: copy_recreate_fw_zones_to_remote
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_fw_zones.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_fw_zones.sh"
    owner: root
    group: root
    mode: '0770'
    backup: yes
  register: copy_recreate_fw_zones_to_remote_res
  when: recreate_fw_zones_sh_exists.stat.exists==true

######################################################

- name: copy_recreate_policies_to_remote
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_policies.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_policies.sh"
    owner: root
    group: root
    mode: '0770'
    backup: yes
  register: copy_recreate_policies_to_remote_res
  when: recreate_policies_sh_exists.stat.exists==true

######################################################

- name: "run 'recreate_ipsets.sh' at remote"
  ansible.builtin.shell: ~/ansible_helpers/conf_firewalld/recreate_ipsets.sh > ~/ansible_helpers/conf_firewalld/recreate_ipsets-res.txt
  when: copy_recreate_ipset_to_remote_res.changed==true

######################################################

- name: "run 'recreate_fw_zones.sh' at remote"
  ansible.builtin.shell: ~/ansible_helpers/conf_firewalld/recreate_fw_zones.sh > ~/ansible_helpers/conf_firewalld/recreate_fw_zones-res.txt
  when: copy_recreate_fw_zones_to_remote_res.changed==true

######################################################

- name: "run 'recreate_policies.sh' at remote"
  ansible.builtin.shell: ~/ansible_helpers/conf_firewalld/recreate_policies.sh > ~/ansible_helpers/conf_firewalld/recreate_policies-res.txt
  when: copy_recreate_policies_to_remote_res.changed==true
