# APPLY IPSET, ZONES, POLICIES
######################################################STEP 1. Check for locally generated fwrules files is exist (begin)
#fill vars: recreate_ipsets_sh_exists, recreate_fw_zones_sh_exists, 
##########  recreate_policies_sh_exists, rollback_fwrules_changes_sh_exists

- name: "if exists 'INV-HOST_recreate_ipsets.sh' for apply"
  delegate_to: localhost
  stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_ipsets.sh"
  register: recreate_ipsets_sh_exists

######

- name: "if exists 'INV-HOST_recreate_fw_zones.sh' for apply"
  delegate_to: localhost
  stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_fw_zones.sh"
  register: recreate_fw_zones_sh_exists

######

- name: "if exists 'INV-HOST_recreate_policies.sh' for apply"
  delegate_to: localhost
  stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_policies.sh"
  register: recreate_policies_sh_exists

######

- name: "if exists 'INV-HOST_rollback_fwrules_changes.sh'"
  delegate_to: localhost
  stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_rollback_fwrules_changes.sh"
  register: rollback_fwrules_changes_sh_exists

######################################################STEP 1. Check for locally generated fwrules files is exist (end)

######################################################STEP 2. Create or remove some files at remote side (begin)

- name: create_dir "~/ansible_helpers/conf_firewalld" if not exists
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld"
    state: directory

######

- name: create_dir "ansible_helpers/conf_firewalld/apply_info" if not exists
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld/appy_info"
    state: directory

######

- name: Remove file "~/ansible_helpers/conf_firewalld/rollback_fwrules_changes.sh" at remote side before run "apply_fwrules.sh"
  ansible.builtin.file:
    path: "~/ansible_helpers/conf_firewalld/rollback_fwrules_changes.sh"
    state: absent

######################################################STEP 2. Create or remove some files at remote side (end)

######################################################STEP 3. Copy recreated fwrules-files and rollback-script to remote if need (begin)

- name: copy_recreate_ipset_to_remote
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_ipsets.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_ipsets.sh"
    owner: root
    group: root
    mode: '0770'
    backup: yes
  register: copy_recreate_ipset_to_remote_res
  when: recreate_ipsets_sh_exists.stat.exists==true

######

- name: copy_recreate_fw_zones_to_remote
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_fw_zones.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_fw_zones.sh"
    owner: root
    group: root
    mode: '0770'
    backup: yes
  register: copy_recreate_fw_zones_to_remote_res
  when: recreate_fw_zones_sh_exists.stat.exists==true

######

- name: copy_recreate_policies_to_remote
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_recreate_policies.sh"
    dest: "~/ansible_helpers/conf_firewalld/recreate_policies.sh"
    owner: root
    group: root
    mode: '0770'
    backup: yes
  register: copy_recreate_policies_to_remote_res
  when: recreate_policies_sh_exists.stat.exists==true

######

- name: copy_rollback_fwrules_changes_to_remote_if_need
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}_rollback_fwrules_changes.sh"
    dest: "~/ansible_helpers/conf_firewalld/rollback_fwrules_changes.sh"
    owner: root
    group: root
    mode: '0770'
  when: rollback_fwrules_changes_sh_exists.stat.exists==true

######

- name: copy_apply_fwrules_sh_to_remote
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/apply_fwrules.sh"
    dest: "~/ansible_helpers/conf_firewalld/apply_fwrules.sh"
    owner: root
    group: root
    mode: '0770'

######################################################STEP 3. Copy recreated fwrules-files and rollback-script to remote if need (end)
