- name: collect and save network data to user home dir
  ansible.builtin.shell: ip -o addr > ~/ansible_helpers/conf_firewalld/ip_addr

######################################################

- name: Create directory for raw network data (network_data-dir)
  ansible.builtin.file:
    path: "{{playbook_dir}}/fwrules_backup_from_remote/network_data"
    state: directory
  delegate_to: localhost

######################################################

- name: fetch_raw_network_data
  ansible.builtin.fetch:
    flat: yes
    src: "~/ansible_helpers/conf_firewalld/{{item}}"
    dest: "{{playbook_dir}}/fwrules_backup_from_remote/network_data/{{inventory_hostname}}_{{item}}"
  with_items:
    - "ip_addr"
