---
- hosts: firewall_conf_dedic_app_v1
  tasks:
######################################################Check for '*_is_run_now'(begin)

    - name: "Check if exists 'apply_fwrules_is_run_now' at remote"
      stat:
        path: "~/ansible_helpers/conf_firewalld/apply_fwrules_is_run_now"
      register: apply_fwrules_is_run_at_remote_now_exists

######

    - name: "Check if exists 'rollback_fwrules_changes_is_run_now' at remote"
      stat:
        path: "~/ansible_helpers/conf_firewalld/rollback_fwrules_changes_is_run_now"
      register: rollback_fwrules_changes_is_run_at_remote_now_exists

######################################################Check for '*_is_run_now'(end)

######################################################Kill rollback/apply_fwrules processes if need and remove content of '~/ansible_helpers/conf_firewalld' (begin)

    - name: "Cancel rollback operation ('rollback_fwrules_changes.sh') at remote if need"
      ansible.builtin.command: "pkill -9 -f rollback_fwrules_changes"
      ignore_errors: yes
      when: rollback_fwrules_changes_is_run_at_remote_now_exists.stat.exists==true

######

    - name: "Cancel apply_fwrules operation ('apply_fwrules.sh') at remote if need"
      ansible.builtin.command: "pkill -9 -f apply_fwrules"
      ignore_errors: yes
      when: apply_fwrules_is_run_at_remote_now_exists.stat.exists==true

######

    - name: "Remove content of '~/ansible_helpers/conf_firewalld' at remote"
      ansible.builtin.raw: "rm -rf ~/ansible_helpers/conf_firewalld/*"
      ignore_errors: yes

######################################################Kill rollback/apply_fwrules processes and remove content of '~/ansible_helpers/conf_firewalld' if need (end)

######################################################Apply firewalld.conf (begin)

    - name: "Run task 'fwrules_apply_fwconfig_task.yml'"
      ansible.builtin.include_tasks: "{{playbook_dir}}/tasks/fwrules_apply_fwconfig_task.yml"

######################################################Apply firewalld.conf (end)

######################################################Apply firewall rules (recreate ipsets/zones/policies) (begin)

    - name: "Run task 'fwrules_apply_task.yml'"
      ansible.builtin.include_tasks: "{{playbook_dir}}/tasks/fwrules_apply_task.yml"

######################################################Apply firewall rules (recreate ipsets/zones/policies) (end)

######################################################Apply '/etc/rsyslog.d/firewalld-droppd.conf' (begin)

    - name: "Run task 'fwrules_apply_droppd_conf_task.yml'"
      ansible.builtin.include_tasks: "{{playbook_dir}}/tasks/fwrules_apply_droppd_conf_task.yml"

######################################################Apply '/etc/rsyslog.d/firewalld-droppd.conf' (end)
