---
- hosts: lxc_server_conf_dedic_app_v1
  tasks:
###Copy and check CFG
    - name: copy_lxc_default_conf_to_remote
      ansible.builtin.copy:
        src: "{{playbook_dir}}/conf/lxc_default.conf"
        dest: /etc/lxc/default.conf
        owner: root
        group: root
        mode: '0644'
        ###COMMENT this if selinux is disabled
        seuser: system_u
        setype: etc_t
        serole: object_r
        selevel: s0
        ###COMMENT this if selinux is disabled
        backup: yes
      register: copy_lxc_default_conf_to_remote_res

######################################################

    - name: copy_lxc_usernet_conf_to_remote
      ansible.builtin.copy:
        src: "{{playbook_dir}}/conf/lxc-usernet"
        dest: /etc/lxc/lxc-usernet
        owner: root
        group: root
        mode: '0644'
        ###COMMENT this if selinux is disabled
        seuser: system_u
        setype: etc_t
        serole: object_r
        selevel: s0
        ###COMMENT this if selinux is disabled
        backup: yes
      register: copy_lxc_usernet_conf_to_remote_res

######################################################

    - name: copy_etc_subuid_to_remote
      ansible.builtin.copy:
        src: "{{playbook_dir}}/conf/lxc_subuid"
        dest: /etc/subuid
        owner: root
        group: root
        mode: '0644'
        ###COMMENT this if selinux is disabled
        seuser: system_u
        setype: etc_t
        serole: object_r
        selevel: s0
        ###COMMENT this if selinux is disabled
        backup: yes
      register: copy_etc_subuid_to_remote_res

######################################################

    - name: copy_etc_subgid_to_remote
      ansible.builtin.copy:
        src: "{{playbook_dir}}/conf/lxc_subgid"
        dest: /etc/subgid
        owner: root
        group: root
        mode: '0644'
        ###COMMENT this if selinux is disabled
        seuser: system_u
        setype: etc_t
        serole: object_r
        selevel: s0
        ###COMMENT this if selinux is disabled
        backup: yes
      register: copy_etc_subgid_to_remote_res

######################################################

    - name: run_cfg_reload_for_lxcfs_services_if_conf_files_changed
      ansible.builtin.systemd:
        name: "{{item}}"
        state: reloaded
        masked: no
      with_items:
        - lxcfs.service
      when: copy_lxc_default_conf_to_remote_res.changed==true or copy_lxc_usernet_conf_to_remote_res.changed==true or copy_etc_subuid_to_remote_res.changed==true or copy_etc_subuid_to_remote_res.changed==true

######################################################

    - name: run_restart_for_lxc_services_if_conf_files_changed
      ansible.builtin.systemd:
        name: "{{item}}"
        state: restarted
        masked: no
      with_items:
        - lxc-net.service
        - lxc.service
      when: copy_lxc_default_conf_to_remote_res.changed==true or copy_lxc_usernet_conf_to_remote_res.changed==true or copy_etc_subuid_to_remote_res.changed==true or copy_etc_subuid_to_remote_res.changed==true

######################################################

    - name: Add_alias_to_bashrc with 'DOWNLOAD_KEYSERVER' for 'lxc-create'
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "alias lxc-create='DOWNLOAD_KEYSERVER=\"keyserver.ubuntu.com\" lxc-create'"
        owner: root
        regexp: "^alias lxc-create='DOWNLOAD_KEYSERVER=\"keyserver.ubuntu.com\" lxc-create'$"
        state: present
        backup: yes
        insertafter: EOF

######################################################

    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
