---
- hosts: rhel7_chrony_client_hosts
  tasks:
    - name: install_chrony_packages
      ansible.builtin.yum:
        name: "{{packages}}"
        state: installed
      vars:
        packages:
        - chrony

######################################################

    - name: check_for_disabled_ntpd
      ansible.builtin.systemd:
        name: ntpd.service
        state: stopped
        enabled: no
      ignore_errors: yes
