---
- hosts: rhel7_chrony_client_conf_dedic_app
  tasks:
    - name: install_chrony_packages
      ansible.builtin.yum:
        name: "{{item}}"
        state: installed
      with_items:
        - chrony

######################################################

    - name: check_for_disabled_ntpd_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        enabled: no
      with_items:
        - ntpd.service
      ignore_errors: yes
