---
- hosts: rhel7_chrony_server_hosts
  tasks:
    - name: enable_n_if_started_chronyd_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        enabled: yes
        masked: no
      with_items:
        - chronyd.service
