---
- hosts: rhel7_chrony_server_hosts
  tasks:
    - name: enable_n_if_started_chronyd
      ansible.builtin.systemd:
        name: chronyd.service
        state: started
        enabled: yes
        masked: no
