---
- hosts: rhel7_chrony_server_hosts
  tasks:
    - name: disable_n_stop_chronyd_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        enabled: no
        masked: no
      with_items:
        - chronyd.service

######################################################

    - name: uninstall_chrony_packages
      ansible.builtin.yum:
        name: "{{item}}"
        state: removed
      with_items:
        - chrony

