---
- hosts: rhel7_chrony_server_conf_dedic_app
  tasks:
    - name: update_chrony_packages
      ansible.builtin.yum:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - chrony
      register: update_chrony_packages_res

######################################################

    - name: restart_chronyd_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: restarted
        enabled: yes
        masked: no
      with_items:
        - chronyd.service
      when: update_chrony_packages_res.changed==true
