---
- hosts: rhel8_lxc_server_conf_dedic_app
  tasks:
    - name: enable_n_if_started_lxc_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        enabled: yes
        masked: no
      with_items:
        - lxc.service
        - lxc-net.service
        - lxcfs.service
