---
- hosts: rhel8_lxc_server_hosts
  tasks:
    - name: enable_n_if_started_lxc_serv
      ansible.builtin.systemd:
        name: lxc.service
        state: started
        enabled: yes
        masked: no

######################################################

    - name: enable_n_if_started_lxc_net_serv
      ansible.builtin.systemd:
        name: lxc-net.service
        state: started
        enabled: yes
        masked: no

######################################################
    
    - name: enable_n_if_started_lxcfs_serv
      ansible.builtin.systemd:
        name: lxcfs.service
        state: started
        enabled: yes
        masked: no
