---
- hosts: rhel8_lxc_server_conf_dedic_app
  tasks:
    - name: install_lxc_packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: installed
      with_items:
        - epel-release
        - python3-lxc
        - debootstrap
        - lxc
        - lxc-libs
        - lxc-templates
        - lxcfs
        - dpkg
        - bridge-utils
        - policycoreutils-python-utils
