---
- hosts: rhel8_lxc_server_hosts
  tasks:
    - name: install_lxc_packages
      ansible.builtin.dnf:
        name: "{{packages}}"
        state: installed
      vars:
        packages:
        - epel-release
        - debootstrap
        - lxc
        - lxc-libs
        - lxc-templates
        - lxcfs
        - dpkg
