---
- hosts: rhel8_lxc_server_hosts
  tasks:
    - name: disable_n_stop_lxc_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        enabled: no
        masked: no
      with_items:
        - lxc.service
        - lxc-net.service
        - lxcfs.service

######################################################

    - name: uninstall_lxc_packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: removed
      with_items:
        - debootstrap
        - python3-lxc
        - lxc
        - lxc-libs
        - lxc-templates
        - lxcfs
        - dpkg
        - bridge-utils
