---
- hosts: rhel8_lxc_server_conf_dedic_app
  tasks:
    - name: update_lxc_packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - epel-release
        - python3-lxc
        - debootstrap
        - lxc
        - lxc-libs
        - lxc-templates
        - lxcfs
        - dpkg
        - bridge-utils
      register: update_lxc_packages_res

######################################################

    - name: restart_lxc_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: restarted
        enabled: yes
        masked: no
      with_items:
        - lxc.service
        - lxc-net.service
        - lxcfs.service
      when: update_lxc_packages_res.changed==true
