---
- hosts: rhel8_firewall_hosts
  tasks:
    - name: "Install 'firewall, procps-ng, rsyslog, conntrack-tools' at remote"
      ansible.builtin.dnf:
        name: "{{item}}"
        state: installed
      with_items:
        - firewalld
        - procps-ng
        - rsyslog
        - conntrack-tools
