---
- hosts: rhel8_firewall_conf_dedic_app
  tasks:
    - name: "Enable and start (if not started) services 'firewalld.service, rsyslog.service' at remote"
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        enabled: yes
        masked: no
      with_items:
        - firewalld.service
        - rsyslog.service
