---
- hosts: rhel8_firewall_hosts
  vars:
     panic_timeout: "{{lookup('file','{{playbook_dir}}/tmp_vars/panic_timeout')}}"
  tasks:
######################################################STEP 1. Check for remote dirs/is_run_now-files is exists (begin)
# fill vars: apply_fwrules_is_run_at_remote_now_exists, rollback_fwrules_changes_is_run_at_remote_now_exists

    - name: "Check if exists 'apply_fwrules_is_run_now' at remote"
      stat:
        path: "~/ansible_helpers/conf_firewalld/apply_fwrules_is_run_now"
      register: apply_fwrules_is_run_at_remote_now_exists

######

    - name: "Check if exists 'rollback_fwrules_changes_is_run_now' at remote"
      stat:
        path: "~/ansible_helpers/conf_firewalld/rollback_fwrules_changes_is_run_now"
      register: rollback_fwrules_changes_is_run_at_remote_now_exists

######################################################STEP 1. Check for remote dirs/is_run_now-files is exists (end)
