---
- hosts: rhel8_firewall_hosts
  tasks:
######APPLY if one of the shell-scripts (recreate_ipsets.sh, recreate_fw_zones.sh, recreate_policies.sh, rollback_fwrules_changes.sh)
###for conf firewalld is copied to remote or firewalld.conf is changed
    - name: "Run 'apply_fwrules.sh' as process at remote"
      ansible.builtin.raw: "nohup sh -c '~/ansible_helpers/conf_firewalld/apply_fwrules.sh >/dev/null 2>&1' & sleep 1"
