---
- hosts: rhel8_firewall_hosts
  tasks:
    - name: "run fwrules_apply_fwconfig_task"
      ansible.builtin.include_tasks: "{{playbook_dir}}/tasks/fwrules_apply_fwconfig_task.yml"

######################################################

    - name: "run fwrules_apply_task"
      ansible.builtin.include_tasks: "{{playbook_dir}}/tasks/fwrules_apply_task.yml"

######################################################

    - name: "run fwrules_apply_droppd_conf_task"
      ansible.builtin.include_tasks: "{{playbook_dir}}/tasks/fwrules_apply_droppd_conf_task.yml"
