# APPLY DROPPD CONF
- name: "Check if exists at localhost 'INV-HOST/rsyslog_firewalld-droppd.conf' for apply"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/rsyslog_firewalld-droppd.conf"
  register: droppd_conf_exists

######################################################

- name: "Copy 'rsyslog_firewalld-droppd.conf' to remote"
  ansible.builtin.copy:
    src: "{{playbook_dir}}/scripts_for_remote/fwrules_files/{{inventory_hostname}}/rsyslog_firewalld-droppd.conf"
    dest: /etc/rsyslog.d/firewalld-droppd.conf
    owner: root
    group: root
    mode: '0644'
    ###COMMENT this if selinux is disabled
    seuser: system_u
    setype: syslog_conf_t
    serole: object_r
    selevel: s0
    ###COMMENT this if selinux is disabled
    backup: yes
  register: copy_droppd_conf_to_remote_res
  when: droppd_conf_exists.stat.exists==true

######################################################

- name: "Enable and restart 'rsyslog.service'"
  ansible.builtin.systemd:
    name: "{{item}}"
    state: restarted
    enabled: yes
    masked: no
  with_items:
    - rsyslog.service
  when: copy_droppd_conf_to_remote_res.changed==true
