---
- hosts: rhel8_nfs_server_hosts
  tasks:
###NFS
    - name: enable_n_if_started_nfs_server_serv
      ansible.builtin.systemd:
        name: nfs-server.service
        state: started
        enabled: yes
        masked: no

######################################################
    
    - name: enable_n_if_started_nfs_idmapd_serv
      ansible.builtin.systemd:
        name: nfs-idmapd.service
        state: started
        enabled: yes
        masked: no
    
######################################################

    - name: enable_n_if_started_nfs_mountd_serv
      ansible.builtin.systemd:
        name: nfs-mountd.service
        state: started
        enabled: yes
        masked: no
    
######################################################

    - name: enable_n_if_started_nfsdcld_serv
      ansible.builtin.systemd:
        name: nfsdcld.service
        state: started
        enabled: yes
        masked: no
    
######################################################

    - name: enable_n_if_started_nfs_client_targ
      ansible.builtin.systemd:
        name: nfs-client.target
        state: started
        enabled: yes
        masked: no
    
######################################################

    - name: enable_n_if_started_nfs_rpc_pipefs_mnt
      ansible.builtin.systemd:
        name: var-lib-nfs-rpc_pipefs.mount
        state: started
        masked: no
    
######################################################

    - name: enable_n_if_started_nfsd_mnt
      ansible.builtin.systemd:
        name: proc-fs-nfsd.mount
        state: started
        masked: no
    
###RPCbind
    - name: enable_n_if_started_rpcbind_serv
      ansible.builtin.systemd:
        name: rpcbind.service
        state: started
        enabled: yes
        masked: no
    
######################################################

    - name: enable_n_if_started_rpcbind_sock
      ansible.builtin.systemd:
        name: rpcbind.socket
        state: started
        enabled: yes
        masked: no
    
######################################################

    - name: enable_n_if_started_rpc_statd_serv
      ansible.builtin.systemd:
        name: rpc-statd.service
        state: started
        enabled: yes
        masked: no
    
######################################################

    - name: enable_n_if_started_rpc_statd_notif_serv
      ansible.builtin.systemd:
        name: rpc-statd-notify.service
        state: started
        enabled: yes
        masked: no
    
######################################################

    - name: enable_n_if_started_rpc_pipefs_targ
      ansible.builtin.systemd:
        name: rpc_pipefs.target
        state: started
        masked: no

######################################################

    - name: check_if_started_rpcbind_targ
      ansible.builtin.systemd:
        name: rpcbind.target
        state: started
        masked: no
      register: rpcbind_targ_res
      ignore_errors: true

######################################################

    - name: run_rpcbin_serv_if_rpcbind_targ_not_started
      ansible.builtin.systemd:
        name: rpcbind.service
        state: restarted
        masked: no
      when: rpcbind_targ_res.failed==true
