---
- hosts: rhel8_nfs_server_conf_dedic_app
  tasks:
###NFS
    - name: enable_n_if_started_nfs_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        enabled: yes
        masked: no
      with_items:
        - nfs-server.service
        - nfs-idmapd.service
        - nfs-mountd.service
        - nfsdcld.service

######################################################

    - name: enable_n_if_started_nfs_targets
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        enabled: yes
        masked: no
      with_items:
        - nfs-client.target
    
######################################################

    - name: if_started_nfs_mounts
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        masked: no
      with_items:
        - var-lib-nfs-rpc_pipefs.mount
        - proc-fs-nfsd.mount
    
######################################################

###RPCbind
    - name: enable_n_if_started_rpcbind_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        enabled: yes
        masked: no
      with_items:
        - rpcbind.service
        - rpc-statd.service
        - rpc-statd-notify.service
    
######################################################

    - name: enable_n_if_started_rpcbind_sock
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        enabled: yes
        masked: no
      with_items:
        - rpcbind.socket
    
######################################################

    - name: if_started_rpc_pipefs_targ
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        masked: no
      with_items:
        - rpc_pipefs.target

######################################################

    - name: check_if_started_rpcbind_targ
      ansible.builtin.systemd:
        name: rpcbind.target
        state: started
        masked: no
      register: rpcbind_targ_res
      ignore_errors: true

######################################################

    - name: run_rpcbin_serv_if_rpcbind_targ_not_started
      ansible.builtin.systemd:
        name: "{{item}}"
        state: restarted
        masked: no
      with_items:
        - rpcbind.service
      when: rpcbind_targ_res.failed==true
