---
- hosts: rhel8_nfs_server_conf_dedic_app
  tasks:
    - name: install_nfs_packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: installed
      with_items:
        - nfs-utils

######################################################

    ###COMMENT this if selinux is disabled
    - name: set_nfs_export_all_rw
      ansible.posix.seboolean:
        name: nfs_export_all_rw
        state: yes
        persistent: yes
    ###COMMENT this if selinux is disabled
