---
- hosts: rhel8_nfs_server_conf_dedic_app
  tasks:
###NFS (systemd)
    - name: disable_n_stop_nfs_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        enabled: no
        masked: no
      with_items:
        - nfs-server.service
        - nfs-idmapd.service
        - nfs-mountd.service
        - nfsdcld.service

######################################################

    - name: disable_n_stop_nfs_targets
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        enabled: no
        masked: no
      with_items:
        - nfs-client.target

######################################################

    - name: stop_nfs_mounts
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        masked: no
      with_items:
        - var-lib-nfs-rpc_pipefs.mount
        - proc-fs-nfsd.mount

######################################################

###RPCbind (systemd)
    - name: disable_n_stop_rpcbind_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        enabled: no
        masked: no
      with_items:
        - rpcbind.service
        - rpc-statd.service
        - rpc-statd-notify.service

######################################################

    - name: disable_n_stop_rpcbind_sockets
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        enabled: no
        masked: no
      with_items:
        - rpcbind.socket

######################################################

    - name: stop_rpc_targets
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        masked: no
      with_items:
        - rpc_pipefs.target
        - rpcbind.target

######################################################

###Set_exports_to_empty
    - name: copy_empty_exports_conf_to_remote
      ansible.builtin.copy:
        src: "{{playbook_dir}}/exports/empty_exports"
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
        ###COMMENT this if selinux is disabled
        seuser: system_u
        setype: exports_t
        serole: object_r
        selevel: s0
        ###COMMENT this if selinux is disabled
        backup: yes

######################################################

###Uninstall package
    - name: uninstall_nfs_packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: removed
      with_items:
        - nfs-utils

######################################################

    ###COMMENT this if selinux is disabled
    - name: unset_nfs_export_all_rw
      ansible.posix.seboolean:
        name: nfs_export_all_rw
        state: no
        persistent: no
    ###COMMENT this if selinux is disabled
