---
- hosts: rhel8_nfs_server_hosts
  tasks:
    - name: update_nfs_packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - nfs-utils
        - rpcbind
      register: update_nfs_packages_res

######################################################

###NFS (systemd)
    - name: restart_nfs_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: restarted
        enabled: yes
        masked: no
      with_items:
        - nfs-server.service
        - nfs-idmapd.service
        - nfs-mountd.service
        - nfsdcld.service
      when: update_nfs_packages_res.changed==true

######################################################

    - name: restart_nfs_targets
      ansible.builtin.systemd:
        name: "{{item}}"
        state: restarted
        enabled: yes
        masked: no
      with_items:
        - nfs-client.target
      when: update_nfs_packages_res.changed==true

######################################################

    - name: restart_nfs_mounts
      ansible.builtin.systemd:
        name: "{{item}}"
        state: restarted
        masked: no
      with_items:
        - var-lib-nfs-rpc_pipefs.mount
        - proc-fs-nfsd.mount
      when: update_nfs_packages_res.changed==true

######################################################

###RPCbind (systemd)
    - name: restart_rpcbind_services
      ansible.builtin.systemd:
        name: "{{item}}"
        state: restarted
        enabled: yes
        masked: no
      with_items:
        - rpcbind.service
        - rpc-statd.service
        - rpc-statd-notify.service
      when: update_nfs_packages_res.changed==true

######################################################

    - name: restart_rpcbind_sockets
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        enabled: yes
        masked: no
      with_items:
        - rpcbind.socket

######################################################

    - name: restart_rpc_pipefs_targ
      ansible.builtin.systemd:
        name: rpc_pipefs.target
        state: restarted
        masked: no
      when: update_nfs_packages_res.changed==true

######################################################

    - name: restart_rpcbind_targ
      ansible.builtin.systemd:
        name: rpcbind.target
        state: started
        masked: no
