
- name: collect and save network data to user home dir
  ansible.builtin.shell: ip -o link | grep -v noqueue > ~/ansible_helpers/conf_int_ipv4_via_network_scripts/ip_link_noqueue && ip neighbour > ~/ansible_helpers/conf_int_ipv4_via_network_scripts/ip_neighbour

######################################################

- name: Create directory for raw network data (network_data-dir)
  ansible.builtin.file:
    path: "{{playbook_dir}}/ifcfg_backup_from_remote/network_data"
    state: directory
  delegate_to: localhost

######################################################

- name: fetch_raw_network_data
  ansible.builtin.fetch:
    flat: yes
    src: "~/ansible_helpers/conf_int_ipv4_via_network_scripts/{{item}}"
    dest: "{{playbook_dir}}/ifcfg_backup_from_remote/network_data/{{inventory_hostname}}_{{item}}"
  with_items:
    - "ip_link_noqueue"
    - "ip_neighbour"
